version: '3'

services:
    web:
        image: nginx:alpine
        volumes:
            - ./public:/public
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8081:80
        networks:
            - nginxphp

    php:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - ./public:/public
        expose:
            - 9000
        networks:
            - nginxphp

networks:
  nginxphp:
